### ISSUE TITLE
Unexpected token < with SSR

### ISSUE THREAD

**Issue by elektrobober** [BUPT-HJM/vue-blog#15]
Hi, @BUPT-HJM, first of all thank you a lot for this project, its pretty nice.
But I face problem while using external library at front end. I need slider functionality for first page with article list. I tried to use:

**-** [https://github.com/NightCatSama/vue-slider-component](https://github.com/NightCatSama/vue-slider-component) - this component export js file, and it use `document` inside it.
My error in this case is - **ReferenceError: document is not defined** while I'm doing
`import slider from 'vue-slider-component'`

**-** My second choice is [https://github.com/ktsn/vue-range-slider](https://github.com/ktsn/vue-range-slider)
My error in this case is - **ReferenceError: window is not defined** while I'm doing
`import 'vue-range-slider/dist/vue-range-slider.css'`

**-** Then I tried to use vue-slider-component another way to connect 
My error in this case is - **SyntaxError: Unexpected token <** while I'm doing
`import vueSlider from 'vue-slider-component/src/vue2-slider.vue'`

So, question is - what is the right and best way to import external component to front-end of your project? 
Thank you forward.

**Comment by BUPT-HJM** [comment]
I am so sorry to reply you late.

As you say, the dist js file from the component(https://github.com/NightCatSama/vue-slider-component) uses `document` inside it, So, we can't use it for Server-Side Rendering.
There is no doubt that we can copy `vue2-slider.vue` file into our project. Surely, it is not a good idea.
Your third choice is right. But It causes error because of `webpack-node-externals`.`webpack-node-externals` will ignore all modules in node_modules folder for the backend bundling.

Now I may fix it by adding the vue file into whitelist. You can see it from https://github.com/BUPT-HJM/vue-blog/commit/fa96e1fe342d9a0328f315e0ce17481394ce9daf.

You can update your repo to try it.

**Comment by elektrobober** [comment]
@BUPT-HJM Thx you a lot, It's work for me now!
